#!/bin/bash -xv

user_local_conf=$(mktemp --dry-run --tmpdir=/tmp userXXX)
local_conf="conf/local.conf"

firefox=( yes no )
cfg_firefox() {
if [[ $1 == "yes" ]];then
cat << EOF >> ${user_local_conf}
# Add Browser
IMAGE_INSTALL_append = " firefox "
EOF
fi
}

rootfs=( ro rw )
cfg_rootfs() {
if [[ $1 == "ro" ]];then
cat << EOF >> ${user_local_conf}
IMAGE_FEATURES += "read-only-rootfs"
EOF
fi
}

declare -A ARRAYNAME=( [firefox]="no" [rootfs]="rw" )

cat << EOF
--- Users' Configurations started ---
EOF

cat << EOF >> ${user_local_conf}
# Users' Configurations
EOF

for ARRAY in ${!ARRAYNAME[@]}; do
select_string='default '
eval array=\${${ARRAY}[@]}
for value in ${array[@]}; do
select_string+=${value}" "
done
PS3="${ARRAY} configuration [ ${ARRAYNAME[${ARRAY}]} ] (Ctrl^C -- exit) : "
select i in $select_string; do
[[ -z ${i} ]] && echo "Invalid option -(" || case $i in
	default)
	break
	;;
	*)
	ARRAYNAME[${ARRAY}]=${i}
	break
	;;
esac
done # select
done # for

for ARRAY in ${!ARRAYNAME[@]}; do
command -v cfg_${ARRAY} &>/dev/null
[[ $? -eq 0 ]] && cfg_${ARRAY} ${ARRAYNAME[${ARRAY}]}
done

if [[ -f ${local_conf} ]];then
cat ${user_local_conf} >> ${local_conf}
fi

rm -rf ${user_local_conf}
